name: Data Pipeline

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:  # Ручной запуск

jobs:
  build:
    runs-on: ubuntu-latest
    env:  # Глобальные переменные окружения
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      # Добавьте другие секреты, если нужны (e.g., DATABASE_URL: ${{ secrets.DATABASE_URL }})

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
        token: ${{ secrets.REPO_ACCESS_TOKEN }}  # Используем PAT для push прав
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Или ваша версия, Prophet требует 3.7+
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt  # Если есть requirements.txt
        # Или напрямую: pip install prophet
        pip install -r requirements.txt  # Добавлены зависимости для модели и визуализаций
        
    - name: Create data directories
      run: |
        mkdir -p data/raw/openweather_api || echo "Failed to create directories"
        
    - name: Run data collection
      run: |
        python scripts/collect_data.py || echo "Data collection script failed"
        
    - name: Verify files after collection
      run: |
        echo "Contents of data/ after collection:"
        ls -la data/ || echo "Data directory not found"
        find data/ -type f -name "*.json" | head -10 || echo "No JSON files found"
        
    - name: Upload data files as artifact after collection
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: collected-data-after-collection
        path: data/
        if-no-files-found: warn

    - name: Run data cleaning
      run: |
        python scripts/clean_data.py || echo "Data cleaning script failed"
        
    - name: Verify files after cleaning
      run: |
        echo "Contents of data/ after cleaning:"
        ls -la data/ || echo "Data directory not found"
        find data/ -type f | head -10 || echo "No files found"
        
    - name: Upload data files as artifact after cleaning
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: collected-data-after-cleaning
        path: data/
        if-no-files-found: warn

    - name: Run data enrichment
      run: |
        python scripts/enrich_data.py || echo "Data enrichment script failed"
        
    - name: Verify files after enrichment
      run: |
        echo "Contents of data/ after enrichment:"
        ls -la data/ || echo "Data directory not found"
        find data/ -type f | head -10 || echo "No files found"
        
    - name: Upload data files as artifact after enrichment
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: collected-data-after-enrichment
        path: data/
        if-no-files-found: warn

    - name: Run report creation
      run: |
        python scripts/create_reports.py || echo "Report creation script failed"
        
    - name: Verify files after reports
      run: |
        echo "Contents of data/ after reports:"
        ls -la data/ || echo "Data directory not found"
        find data/ -type f | head -10 || echo "No files found"
        
    - name: Upload data files as artifact after reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: collected-data-after-reports
        path: data/
        if-no-files-found: warn

    - name: Upload full logs as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: workflow-logs
        path: .  # Или укажите конкретный файл логов, если скрипты пишут в него
        if-no-files-found: warn
    
    - name: Train weather model and generate forecasts
      run: |
        python scripts/train_weather_model.py  # Исправлено: скрипт в scripts/, запускает обучение, прогноз и визуализации
        
    - name: Verify files after training and visualizations
      run: |
        echo "Contents of data/ after training:"
        ls -la data/ || echo "Data directory not found"
        find data/ -type f | head -10 || echo "No files found"
        
    - name: Update README with visualizations
      run: |
        # Добавляет секцию с визуализациями в конец README.md
        echo "" >> README.md
        echo "## Визуализации" >> README.md
        echo "![Comfort Index](data/visualizations/comfort_index.png)" >> README.md
        echo "![Temperature](data/visualizations/temperature.png)" >> README.md  # Добавь больше, если нужно
    
    - name: Add, commit, and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/models/ data/visualizations/ README.md  # Добавляет прогнозы, визуализации и README
        git status  # Покажет, что добавлено
        git commit -m "Update forecasts, visualizations, and README" || echo "No changes to commit"
        git push https://${{ github.actor }}:${{ secrets.PAT }}@github.com/${{ github.repository }}.git ${{ github.ref_name }}
    
    - name: Verify push
      run: echo "Push completed. Check repo for changes."
