name: Data Pipeline

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:  # Ручной запуск

jobs:
  build:
    runs-on: ubuntu-latest
    env:  # Глобальные переменные окружения для API-ключей (замените на ваши секреты)
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
      

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Или ваша версия
        

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas # Замените на ваши реальные пакеты (например, добавьте openpyxl или matplotlib, если нужны)

    - name: Run data collection
      run: python collect_data.py

    - name: Run data cleaning
      run: python clean_data.py

    - name: Run data enrichment
      run: python enrich_data.py

    - name: Run report creation
      run: python create_reports.py
