name: Data Pipeline

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:  # Ручной запуск

jobs:
  build:
    runs-on: ubuntu-latest
    env:  # Глобальные переменные окружения для API-ключей (замените на ваши секреты)
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
      

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Или ваша версия
        

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas # Замените на ваши реальные пакеты (например, добавьте openpyxl или matplotlib, если нужны)

    - name: Create data directories  # Создаёт папки, если их нет
      run: |
        mkdir -p data
        mkdir -p data/raw/openweather_api

    - name: Verify data directories  # <-- Новый шаг: Проверяет, создались ли папки
      run: ls -la data/  # Выведет содержимое в логи; если папки нет, будет ошибка

    - name: Run data collection
      run: python scripts/collect_data.py
      
    - name: Verify after collection  # <-- Новый шаг: Проверяет после сбора данных
      run: ls -la data/
      
    - name: Upload data files as artifact after collection
      if: success()  # Загружает только при успехе (чтобы не загружать пустое при ошибке)
      uses: actions/upload-artifact@v4
      with:
        name: collected-data-after-collection
        path: data/

    - name: Run data cleaning
      run: python scripts/clean_data.py
      
    - name: Verify after cleaning  # <-- Новый шаг: Проверяет после очистки
      run: ls -la data/
      
    - name: Upload data files as artifact after cleaning
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: collected-data-after-cleaning
        path: data/
        
    - name: Run data enrichment
      run: python scripts/enrich_data.py
      
    - name: Verify after enrichment  # <-- Новый шаг: Проверяет после обогащения
      run: ls -la data/
      
    - name: Upload data files as artifact after enrichment
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: collected-data-after-enrichment
        path: data/
        
    - name: Run report creation
      run: python scripts/create_reports.py
      
    - name: Verify after reports  # <-- Новый шаг: Проверяет после отчётов
      run: ls -la data/
      
    - name: Upload data files as artifact after reports
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: collected-data-after-reports
        path: data/
