name: Data Pipeline

on:
  schedule:
    - cron: '0 * * *'  # Каждый час
  workflow_dispatch:  # Ручной запуск

jobs:
  build:
    runs-on: ubuntu-latest
    env:  # Глобальные переменные окружения
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      # Добавьте другие секреты, если нужны (e.g., DATABASE_URL: ${{ secrets.DATABASE_URL }})

    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v4
      with:
        submodules: false
        token: ${{ secrets.REPO_ACCESS_TOKEN }}  # Используем PAT для push прав
        fetch-depth: 0  # Полная история для корректного merge/pull
    - name: Checkout ready
      if: steps.checkout.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Set up Python
      id: setup_python
      if: steps.checkout.outputs.ready == 'true'
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Или ваша версия, Prophet требует 3.7+
    - name: Python setup ready
      if: steps.setup_python.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Pull latest changes to avoid stale info
      id: pull_changes
      if: steps.setup_python.outputs.ready == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull --rebase origin ${{ github.ref_name }} || (echo "Rebase failed, check for conflicts" && exit 1)
    - name: Pull ready
      if: steps.pull_changes.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Install dependencies
      id: install_deps
      if: steps.pull_changes.outputs.ready == 'true'
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt  # Если есть requirements.txt
        pip install tabulate  # Добавлено для исправления ошибки в update_readme.py
        # Или напрямую: pip install prophet
        # pip install -r requirements.txt  # Удалено дублирование
    - name: Dependencies ready
      if: steps.install_deps.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Create data directories
      id: create_dirs
      if: steps.install_deps.outputs.ready == 'true'
      run: |
        mkdir -p data/raw/openweather_api data/models data/models/forecast data/visualizations || echo "Failed to create directories"
    - name: Directories ready
      if: steps.create_dirs.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Check if API key is available
      id: check_api
      if: steps.create_dirs.outputs.ready == 'true'
      run: |
        if [ -n "$OPENWEATHER_API_KEY" ]; then
          echo "has_api_key=true" >> $GITHUB_OUTPUT
        else
          echo "has_api_key=false" >> $GITHUB_OUTPUT
          echo "API key not available. Skipping data collection."
        fi
    - name: API check ready
      if: steps.check_api.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Run data collection
      id: run_collection
      if: steps.check_api.outputs.ready == 'true' && steps.check_api.outputs.has_api_key == 'true'
      run: |
        python scripts/collect_data.py || echo "Data collection script failed"
    - name: Collection ready
      if: steps.run_collection.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Verify files after collection
      id: verify_collection
      if: steps.run_collection.outputs.ready == 'true'
      run: |
        echo "Contents of data/ after collection:"
        ls -la data/ || echo "Data directory not found"
        find data/ -type f -name "*.json" | head -10 || echo "No JSON files found"
    - name: Verification collection ready
      if: steps.verify_collection.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Upload data files as artifact after collection
      id: upload_collection
      if: steps.verify_collection.outputs.ready == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: collected-data-after-collection
        path: data/
        if-no-files-found: warn
    - name: Upload collection ready
      if: steps.upload_collection.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Check if raw files exist for cleaning
      id: check_raw
      if: steps.upload_collection.outputs.ready == 'true'
      run: |
        if [ -n "$(find data/ -type f -name "*.json" | head -1)" ]; then
          echo "has_raw_files=true" >> $GITHUB_OUTPUT
        else
          echo "has_raw_files=false" >> $GITHUB_OUTPUT
          echo "No raw files found. Skipping data cleaning."
        fi
    - name: Raw check ready
      if: steps.check_raw.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Run data cleaning
      id: run_cleaning
      if: steps.check_raw.outputs.ready == 'true' && steps.check_raw.outputs.has_raw_files == 'true'
      run: |
        python scripts/clean_data.py || echo "Data cleaning script failed"
    - name: Cleaning ready
      if: steps.run_cleaning.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Verify files after cleaning
      id: verify_cleaning
      if: steps.run_cleaning.outputs.ready == 'true'
      run: |
        echo "Contents of data/ after cleaning:"
        ls -la data/ || echo "Data directory not found"
        find data/ -type f | head -10 || echo "No files found"
    - name: Verification cleaning ready
      if: steps.verify_cleaning.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Upload data files as artifact after cleaning
      id: upload_cleaning
      if: steps.verify_cleaning.outputs.ready == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: collected-data-after-cleaning
        path: data/
        if-no-files-found: warn
    - name: Upload cleaning ready
      if: steps.upload_cleaning.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Check if cleaned files exist for enrichment
      id: check_cleaned
      if: steps.upload_cleaning.outputs.ready == 'true'
      run: |
        if [ -n "$(find data/ -type f | head -1)" ]; then
          echo "has_cleaned_files=true" >> $GITHUB_OUTPUT
        else
          echo "has_cleaned_files=false" >> $GITHUB_OUTPUT
          echo "No cleaned files found. Skipping data enrichment."
        fi
    - name: Cleaned check ready
      if: steps.check_cleaned.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Run data enrichment
      id: run_enrichment
      if: steps.check_cleaned.outputs.ready == 'true' && steps.check_cleaned.outputs.has_cleaned_files == 'true'
      run: |
        python scripts/enrich_data.py || echo "Data enrichment script failed"
    - name: Enrichment ready
      if: steps.run_enrichment.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Verify files after enrichment
      id: verify_enrichment
      if: steps.run_enrichment.outputs.ready == 'true'
      run: |
        echo "Contents of data/ after enrichment:"
        ls -la data/ || echo "Data directory not found"
        find data/ -type f | head -10 || echo "No files found"
    - name: Verification enrichment ready
      if: steps.verify_enrichment.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Upload data files as artifact after enrichment
      id: upload_enrichment
      if: steps.verify_enrichment.outputs.ready == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: collected-data-after-enrichment
        path: data/
        if-no-files-found: warn
    - name: Upload enrichment ready
      if: steps.upload_enrichment.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Check if enriched files exist for reports
      id: check_enriched
      if: steps.upload_enrichment.outputs.ready == 'true'
      run: |
        if [ -n "$(find data/ -type f | head -1)" ]; then
          echo "has_enriched_files=true" >> $GITHUB_OUTPUT
        else
          echo "has_enriched_files=false" >> $GITHUB_OUTPUT
          echo "No enriched files found. Skipping report creation."
        fi
    - name: Enriched check ready
      if: steps.check_enriched.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Run report creation
      id: run_reports
      if: steps.check_enriched.outputs.ready == 'true' && steps.check_enriched.outputs.has_enriched_files == 'true'
      run: |
        python scripts/create_reports.py || echo "Report creation script failed"
    - name: Reports ready
      if: steps.run_reports.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Verify files after reports
      id: verify_reports
      if: steps.run_reports.outputs.ready == 'true'
      run: |
        echo "Contents of data/ after reports:"
        ls -la data/ || echo "Data directory not found"
        find data/ -type f | head -10 || echo "No files found"
    - name: Verification reports ready
      if: steps.verify_reports.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Upload data files as artifact after reports
      id: upload_reports
      if: steps.verify_reports.outputs.ready == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: collected-data-after-reports
        path: data/
        if-no-files-found: warn
    - name: Upload reports ready
      if: steps.upload_reports.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Upload full logs as artifact
      id: upload_logs
      if: steps.upload_reports.outputs.ready == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: workflow-logs
        path: .  # Или укажите конкретный файл логов, если скрипты пишут в него
        if-no-files-found: warn
    - name: Upload logs ready
      if: steps.upload_logs.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Check if files exist for training
      id: check_for_train
      if: steps.upload_logs.outputs.ready == 'true'
      run: |
        if [ -n "$(find data/ -type f | head -1)" ]; then
          echo "has_files_for_train=true" >> $GITHUB_OUTPUT
        else
          echo "has_files_for_train=false" >> $GITHUB_OUTPUT
          echo "No files found after reports. Skipping training."
        fi
    - name: Train check ready
      if: steps.check_for_train.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Train weather model and generate forecasts
      id: train_model
      if: steps.check_for_train.outputs.ready == 'true' && steps.check_for_train.outputs.has_files_for_train == 'true'
      run: |
        python scripts/train_weather_model.py  # Исправлено: скрипт в scripts/, запускает обучение, прогноз и визуализации
    - name: Training ready
      if: steps.train_model.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Check directories
      id: check_dirs
      if: steps.train_model.outputs.ready == 'true'
      run: |
        echo "Checking data/ directory:"
        ls -la data/ || echo "data/ directory not found"
        echo "Checking data/models/ directory:"
        ls -la data/models/ || echo "data/models/ directory does not exist or is empty"
        echo "Checking data/models/forecast/ directory:"
        ls -la data/models/forecast/ || echo "data/models/forecast/ directory does not exist or is empty"
        echo "Checking data/visualizations/ directory:"
        ls -la data/visualizations/ || echo "data/visualizations/ directory does not exist or is empty"
    - name: Directories check ready
      if: steps.check_dirs.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Verify files after reports
      id: verify_after_train
      if: steps.check_dirs.outputs.ready == 'true'
      run: |
        echo "Contents of data/ after reports:"
        ls -la data/ || echo "Data directory not found"
        echo "All files in data/ (sorted by modification time):"
        find data/ -type f -printf '%T@ %p\n' | sort -n | cut -d' ' -f2- || echo "No files found"
        echo "Aggregated files specifically:"
        find data/aggregated/ -type f || echo "No aggregated files found"
    - name: Verification after train ready
      if: steps.verify_after_train.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Check if aggregated files exist for visualizations
      id: check_aggregated
      if: steps.verify_after_train.outputs.ready == 'true'
      run: |
        if [ -n "$(find data/aggregated -type f | head -1)" ]; then
          echo "has_aggregated_files=true" >> $GITHUB_OUTPUT
        else
          echo "has_aggregated_files=false" >> $GITHUB_OUTPUT
          echo "No aggregated files found. Skipping visualizations."
        fi
    - name: Aggregated check ready
      if: steps.check_aggregated.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Generate visualizations
      id: generate_viz
      if: steps.check_aggregated.outputs.ready == 'true' && steps.check_aggregated.outputs.has_aggregated_files == 'true'
      run: |
        python scripts/generate_visualizations.py || echo "Visualization generation failed"
    - name: Visualizations ready
      if: steps.generate_viz.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Verify files after visualizations
      id: verify_viz
      if: steps.generate_viz.outputs.ready == 'true'
      run: |
        echo "Contents of data/visualizations/ after visualizations:"
        ls -la data/visualizations/ || echo "data/visualizations/ directory not found"
        find data/visualizations/ -type f | head -10 || echo "No visualization files found"
    - name: Verification viz ready
      if: steps.verify_viz.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Update README with weather data
      id: update_readme
      if: steps.verify_viz.outputs.ready == 'true'
      run: |
        python scripts/update_readme.py || echo "Failed to update README"
    - name: README ready
      if: steps.update_readme.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Add, commit, and push changes
      id: commit_push
      if: steps.update_readme.outputs.ready == 'true'
      run: |
        git add .  # Добавляет все изменения (модели, визуализации, README и т.д.)
        git status  # Покажет, что добавлено
        if ! git diff --staged --quiet; then
          git commit -m "Update forecasts, visualizations, and README"
          # Убираем --force-with-lease, чтобы избежать перезаписи; используем обычный push
          git push https://${{ github.actor }}:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.ref_name }}
          echo "Changes committed and pushed."
        else
          echo "No changes to commit."
        fi
    - name: Commit push ready
      if: steps.commit_push.outcome == 'success'
      run: echo "ready=true" >> $GITHUB_OUTPUT

    - name: Verify push
      if: steps.commit_push.outputs.ready == 'true'
      run: echo "Workflow completed. Check repository for changes."
